/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/assistant`; params?: Router.UnknownInputParams; } | { pathname: `/auth-gateway`; params?: Router.UnknownInputParams; } | { pathname: `/edit-profile`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/legal`; params?: Router.UnknownInputParams; } | { pathname: `/location`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/map`; params?: Router.UnknownInputParams; } | { pathname: `/medical-id`; params?: Router.UnknownInputParams; } | { pathname: `/profile-guest`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/show-staff`; params?: Router.UnknownInputParams; } | { pathname: `/sos`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/__tests__/legal.test`; params?: Router.UnknownInputParams; } | { pathname: `/__tests__/login.test`; params?: Router.UnknownInputParams; } | { pathname: `/__tests__/medicalIdStorage.test`; params?: Router.UnknownInputParams; } | { pathname: `/__tests__/profileStorage.test`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/assistant`; params?: Router.UnknownOutputParams; } | { pathname: `/auth-gateway`; params?: Router.UnknownOutputParams; } | { pathname: `/edit-profile`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/legal`; params?: Router.UnknownOutputParams; } | { pathname: `/location`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/map`; params?: Router.UnknownOutputParams; } | { pathname: `/medical-id`; params?: Router.UnknownOutputParams; } | { pathname: `/profile-guest`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/show-staff`; params?: Router.UnknownOutputParams; } | { pathname: `/sos`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/__tests__/legal.test`; params?: Router.UnknownOutputParams; } | { pathname: `/__tests__/login.test`; params?: Router.UnknownOutputParams; } | { pathname: `/__tests__/medicalIdStorage.test`; params?: Router.UnknownOutputParams; } | { pathname: `/__tests__/profileStorage.test`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/assistant${`?${string}` | `#${string}` | ''}` | `/auth-gateway${`?${string}` | `#${string}` | ''}` | `/edit-profile${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/legal${`?${string}` | `#${string}` | ''}` | `/location${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/map${`?${string}` | `#${string}` | ''}` | `/medical-id${`?${string}` | `#${string}` | ''}` | `/profile-guest${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/show-staff${`?${string}` | `#${string}` | ''}` | `/sos${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/__tests__/legal.test${`?${string}` | `#${string}` | ''}` | `/__tests__/login.test${`?${string}` | `#${string}` | ''}` | `/__tests__/medicalIdStorage.test${`?${string}` | `#${string}` | ''}` | `/__tests__/profileStorage.test${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/assistant`; params?: Router.UnknownInputParams; } | { pathname: `/auth-gateway`; params?: Router.UnknownInputParams; } | { pathname: `/edit-profile`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/legal`; params?: Router.UnknownInputParams; } | { pathname: `/location`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/map`; params?: Router.UnknownInputParams; } | { pathname: `/medical-id`; params?: Router.UnknownInputParams; } | { pathname: `/profile-guest`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/show-staff`; params?: Router.UnknownInputParams; } | { pathname: `/sos`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/__tests__/legal.test`; params?: Router.UnknownInputParams; } | { pathname: `/__tests__/login.test`; params?: Router.UnknownInputParams; } | { pathname: `/__tests__/medicalIdStorage.test`; params?: Router.UnknownInputParams; } | { pathname: `/__tests__/profileStorage.test`; params?: Router.UnknownInputParams; };
    }
  }
}
