VENUES = [
    {
        "venue_id": "v_1001",
        "name": "Central Park Urgent Care",
        "venue_type": "clinic",
        "latitude": 40.785091,
        "longitude": -73.968285,
        "borough": "Manhattan",
        "language_tags": ["EN", "FR"],
        "primary_language": "EN",
        "secondary_language": "FR",
        "accessible_status": "full_access",
        "accessibility_features": ["ramp", "lift", "automatic_door", "disabled_toilet"],
        "active_warning": False,
        "live_report_count": 0,
        "busyness_level": "quiet",
        "busyness_percent": 24,
        "avg_wait_minutes": 5,
        "open_now": True,
        "weather_risk": "low",
    },
    {
        "venue_id": "v_1002",
        "name": "Brooklyn Bridge Pharmacy",
        "venue_type": "pharmacy",
        "latitude": 40.706086,
        "longitude": -73.996864,
        "borough": "Brooklyn",
        "language_tags": ["EN", "ES"],
        "primary_language": "EN",
        "secondary_language": "ES",
        "accessible_status": "partial",
        "accessibility_features": ["ramp", "disabled_toilet"],
        "active_warning": True,
        "live_report_count": 2,
        "busyness_level": "moderate",
        "busyness_percent": 53,
        "avg_wait_minutes": 12,
        "open_now": True,
        "weather_risk": "medium",
    },
    {
        "venue_id": "v_1003",
        "name": "Queens Transit Hub",
        "venue_type": "clinic",
        "latitude": 40.749825,
        "longitude": -73.797634,
        "borough": "Queens",
        "language_tags": ["EN", "ZH"],
        "primary_language": "EN",
        "secondary_language": "ZH",
        "accessible_status": "step_free_route_only",
        "accessibility_features": ["step_free_route"],
        "active_warning": True,
        "live_report_count": 1,
        "busyness_level": "busy",
        "busyness_percent": 81,
        "avg_wait_minutes": 7,
        "open_now": False,
        "weather_risk": "high",
    },
]

REPORTS = [
    {
        "report_id": "r_501",
        "venue_id": "v_1002",
        "issue_type": "wheelchair_lift_broken",
        "latitude": 40.706086,
        "longitude": -73.996864,
        "status": "active",
        "confirmation_count": 2,
        "expires_in_minutes": 95,
        "created_at": "2026-05-28T10:00:00Z",
        "reported_by": "anonymous",
        "badge_text": "Multiple users confirm",
    },
    {
        "report_id": "r_502",
        "venue_id": "v_1003",
        "issue_type": "large_crowd",
        "latitude": 40.749825,
        "longitude": -73.797634,
        "status": "active",
        "confirmation_count": 0,
        "expires_in_minutes": 120,
        "created_at": "2026-05-28T10:30:00Z",
        "reported_by": "anonymous",
        "badge_text": "Live report",
    },
]

REPORT_TEMPLATE = {
    "status": "accepted",
    "report_id": "r_new",
    "message": "Report queued for validation.",
}
